---
- name: Unifi list hosts
  hosts: localhost
  vars_files:
    - secrets.yml
  vars:
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  tasks:
    - name: Get all hosts
      unifi_api:
        endpoint: "hosts"
        method: GET
        headers: "{{ headers }}"
        api_key: "{{ unifi_api_key }}"
      register: result_hosts
    
    - name: Debug all hosts
      debug:
        var: result_hosts
